import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for BeforeYouSign. Read the conditions governing your use of the Platform.",
};

const EFFECTIVE_DATE = "July 5, 2026";
const CREATOR = "Srinivas Jangiti";
const CONTACT_EMAIL = "srinivasajan.work@gmail.com";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
        {/* Header */}
        <div className="mb-10 border-b border-stone-200 pb-8">
          <span className="text-xs font-mono uppercase tracking-widest text-stone-400">
            Legal
          </span>
          <h1 className="mt-2 text-3xl sm:text-4xl font-bold text-stone-900 leading-tight">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-stone-500">
            Effective Date: {EFFECTIVE_DATE}
          </p>
        </div>

        <div className="prose prose-stone max-w-none space-y-8 text-stone-700 text-[15px] leading-7">

          <section>
            <p>
              These Terms of Service (&quot;Terms&quot;) constitute a legally binding
              agreement between you (&quot;User&quot;, &quot;you&quot;, or &quot;your&quot;) and{" "}
              {CREATOR} (&quot;Creator&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), the individual
              operating BeforeYouSign (the &quot;Platform&quot;). By accessing or using
              the Platform in any manner, you unconditionally agree to be bound
              by these Terms. If you do not agree, you must immediately cease
              all use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">1. Nature of the Platform</h2>
            <p>
              BeforeYouSign is an experimental, AI-powered contract analysis
              tool developed for educational and informational purposes. It is
              not a law firm, legal service provider, or regulated legal
              practice. All outputs are generated by automated AI systems and
              do not constitute legal advice, legal opinion, or a
              client-attorney relationship of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">2. Eligibility</h2>
            <p>
              You must be at least 18 years of age and legally capable of
              entering into binding agreements to use the Platform. By using
              the Platform, you represent and warrant that you meet these
              requirements.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">3. Permitted Use</h2>
            <p>You agree to use the Platform solely for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc pl-5 mt-3 space-y-2">
              <li>use the Platform for any unlawful, fraudulent, or harmful purpose;</li>
              <li>upload documents containing malware, illegal content, or content that violates third-party rights;</li>
              <li>attempt to reverse-engineer, scrape, or systematically extract data from the Platform;</li>
              <li>misrepresent AI-generated analysis as professional legal advice;</li>
              <li>circumvent any security measures or access controls of the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">4. Disclaimer of Warranties</h2>
            <p>
              The Platform is provided &quot;<strong>AS IS</strong>&quot; and &quot;<strong>AS AVAILABLE</strong>&quot;
              without warranty of any kind. To the maximum extent permitted by
              applicable law, {CREATOR} expressly disclaims all warranties,
              express or implied, including without limitation warranties of
              merchantability, fitness for a particular purpose, accuracy,
              completeness, reliability, non-infringement, or uninterrupted
              availability. No representation or warranty is made that the
              Platform will be error-free, virus-free, or free from harmful
              components.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">5. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law,{" "}
              <strong>{CREATOR}</strong> — in any personal, professional, or
              academic capacity — shall not be liable to you or any third party
              for any loss, damage, cost, claim, demand, or expense of any
              nature arising from or in connection with:
            </p>
            <ul className="list-disc pl-5 mt-3 space-y-2">
              <li>your use of or reliance on the Platform or its outputs;</li>
              <li>any decision taken or not taken based on AI-generated analysis;</li>
              <li>loss of data, revenue, profit, business, goodwill, or anticipated savings;</li>
              <li>any direct, indirect, incidental, special, consequential, or punitive damages;</li>
              <li>any legal, regulatory, or contractual consequence resulting from your use of the Platform;</li>
              <li>service interruptions, downtime, or technical failures.</li>
            </ul>
            <p className="mt-4">
              This limitation applies regardless of the theory of liability
              (contract, tort, statute, or otherwise) and even if {CREATOR}
              has been advised of the possibility of such damages.{" "}
              <strong>
                In no event shall {CREATOR}&apos;s aggregate liability to you
                exceed zero Indian Rupees (₹0), it being understood that the
                Platform is made available without charge and without any
                commercial relationship.
              </strong>
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">6. Indemnification</h2>
            <p>
              You shall indemnify, defend, and hold {CREATOR} harmless from and
              against any claims, liabilities, damages, judgments, awards,
              losses, costs, expenses, or fees (including reasonable legal fees)
              arising out of or relating to your violation of these Terms or
              your use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">7. Intellectual Property</h2>
            <p>
              All Platform code, design, text, and original content are the
              intellectual property of {CREATOR} unless otherwise indicated.
              You are granted a limited, non-exclusive, non-transferable,
              revocable licence to access and use the Platform solely for
              personal, non-commercial purposes. No rights are transferred to
              you beyond this limited licence.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">8. Uploaded Content</h2>
            <p>
              You retain ownership of any documents you upload. By uploading,
              you grant the Platform a limited, temporary licence to process
              the document solely to generate your requested output. You
              represent and warrant that you have full right, title, and
              authority to upload such documents and that doing so does not
              violate any applicable law, contractual obligation, or
              third-party right.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">9. Termination</h2>
            <p>
              {CREATOR} reserves the right to suspend or terminate your access
              to the Platform at any time, with or without notice, for any
              reason, including but not limited to violation of these Terms.
              Termination does not affect any rights or obligations accrued
              prior to termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">10. Governing Law &amp; Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of India. Any dispute arising under or in connection
              with these Terms shall be submitted to the exclusive jurisdiction
              of the competent courts located in India. You waive any objection
              to such jurisdiction on grounds of inconvenient forum or
              otherwise.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">11. Entire Agreement &amp; Severability</h2>
            <p>
              These Terms, together with the Privacy Policy and Legal
              Disclaimer, constitute the entire agreement between you and{" "}
              {CREATOR} with respect to the Platform. If any provision is held
              invalid or unenforceable, the remaining provisions shall remain
              in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">12. Amendments</h2>
            <p>
              {CREATOR} reserves the right to modify these Terms at any time
              without prior notice. Your continued use of the Platform following
              any modification constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">13. Contact</h2>
            <p>
              For any queries regarding these Terms, contact:{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="text-stone-900 underline"
              >
                {CONTACT_EMAIL}
              </a>
            </p>
          </section>

          {/* Warning box */}
          <div className="mt-10 rounded-lg border border-stone-200 bg-stone-100 p-5">
            <p className="text-sm font-semibold text-stone-800 mb-1">
              Important Notice
            </p>
            <p className="text-sm text-stone-600">
              BeforeYouSign does not provide legal advice. Always consult a
              qualified, licensed legal professional before signing any contract
              or making any legal or financial decision.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
