import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Disclaimer",
  description:
    "Legal disclaimer for BeforeYouSign. The platform and its creator provide no legal advice and accept no liability of any kind.",
};

const EFFECTIVE_DATE = "July 5, 2026";
const CREATOR = "Srinivas Jangiti";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
        {/* Header */}
        <div className="mb-10 border-b border-stone-200 pb-8">
          <span className="text-xs font-mono uppercase tracking-widest text-stone-400">
            Legal
          </span>
          <h1 className="mt-2 text-3xl sm:text-4xl font-bold text-stone-900 leading-tight">
            Legal Disclaimer
          </h1>
          <p className="mt-3 text-sm text-stone-500">
            Effective Date: {EFFECTIVE_DATE}
          </p>
        </div>

        <div className="prose prose-stone max-w-none space-y-8 text-stone-700 text-[15px] leading-7">

          {/* 1 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">1. Not Legal Advice</h2>
            <p>
              BeforeYouSign (the &quot;Platform&quot;) and all content, outputs, analysis,
              summaries, suggestions, risk scores, clause interpretations, or
              recommendations generated by or through the Platform are provided
              strictly for general informational and educational purposes only.
              Nothing on the Platform constitutes, or should be construed as,
              legal advice, legal opinion, the practice of law, or the
              establishment of an attorney–client relationship of any kind,
              whether express, implied, or otherwise.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">2. Complete Exclusion of Liability — Individual Creator</h2>
            <p>
              <strong>{CREATOR}</strong>, the individual who designed, developed,
              and maintains the Platform in a personal and non-commercial
              academic capacity (&quot;Creator&quot;), hereby expressly disclaims, to the
              fullest extent permitted by applicable law, any and all liability,
              responsibility, obligation, or duty of care — whether arising in
              contract, tort (including negligence or strict liability),
              statute, equity, or any other legal or equitable theory — in
              connection with:
            </p>
            <ul className="list-disc pl-5 mt-3 space-y-2">
              <li>any use, misuse, or reliance on the Platform or its outputs;</li>
              <li>any decision made, action taken, or omission made by any person
                based on information obtained from the Platform;</li>
              <li>any loss of profit, revenue, business, data, goodwill, or
                anticipated savings;</li>
              <li>any direct, indirect, incidental, special, consequential,
                punitive, or exemplary damages of any nature whatsoever;</li>
              <li>any legal proceedings, disputes, penalties, fines, or adverse
                outcomes arising from the use of or reliance on the
                Platform&apos;s analysis;</li>
              <li>any inaccuracy, incompleteness, error, omission, or
                misinterpretation in any AI-generated output;</li>
              <li>any failure of the Platform to function as expected, including
                downtime, data loss, or technical errors.</li>
            </ul>
            <p className="mt-4">
              This exclusion applies regardless of whether {CREATOR} was advised
              of the possibility of such damages or losses, and regardless of
              the cause of action or the form in which it is brought.{" "}
              <strong>
                Under no circumstances shall {CREATOR} be personally liable to
                any user, third party, entity, or authority for any claim,
                demand, cost, expense, or liability arising out of or related
                to the Platform.
              </strong>
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">3. AI Limitations — No Warranty</h2>
            <p>
              The Platform employs artificial intelligence and large language
              model technologies that are inherently probabilistic. Outputs may
              contain errors, hallucinations, omissions, or outdated
              information. The Platform is provided on an &quot;<strong>AS IS</strong>&quot;
              and &quot;<strong>AS AVAILABLE</strong>&quot; basis, without warranty of any
              kind, express or implied, including but not limited to warranties
              of merchantability, fitness for a particular purpose,
              non-infringement, accuracy, reliability, or completeness. No oral
              or written information or advice given by the Creator or the
              Platform shall create any warranty.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">4. User Responsibility</h2>
            <p>
              By accessing or using the Platform, you acknowledge and agree
              that: (a) you are solely and exclusively responsible for all
              decisions made in reliance on the Platform&apos;s outputs; (b) you
              will independently verify all information with a qualified,
              licensed legal professional before taking any legal, commercial,
              or financial action; and (c) you assume all risk associated with
              your use of the Platform.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">5. Third-Party Services</h2>
            <p>
              The Platform may integrate with or depend upon third-party
              services, APIs, or models. {CREATOR} is not responsible for the
              availability, accuracy, or reliability of any third-party service,
              and accepts no liability for any harm caused by third-party
              systems, outages, or changes in service terms.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">6. Jurisdictional Limitations</h2>
            <p>
              Legal analysis generated by the Platform may not reflect the laws
              or regulations of your jurisdiction. The Platform makes no
              representation that its content is appropriate or lawful in any
              particular location. Users access the Platform at their own
              initiative and are solely responsible for compliance with local
              laws.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">7. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless {CREATOR} from
              and against any and all claims, liabilities, damages, losses,
              costs, and expenses (including reasonable legal fees) arising out
              of or in any way connected with your use of the Platform, your
              violation of these terms, or your violation of any rights of any
              third party.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">8. Severability</h2>
            <p>
              If any provision of this Disclaimer is held to be invalid,
              illegal, or unenforceable by a court of competent jurisdiction,
              such provision shall be modified to the minimum extent necessary
              to make it enforceable, and the remaining provisions shall
              continue in full force and effect.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">9. Governing Law</h2>
            <p>
              This Disclaimer shall be governed by and construed in accordance
              with the laws of India, without regard to conflict-of-law
              principles. Any dispute arising hereunder shall be subject to the
              exclusive jurisdiction of the competent courts of India.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-lg font-semibold text-stone-900 mb-3">10. Amendments</h2>
            <p>
              {CREATOR} reserves the right to modify this Disclaimer at any
              time without prior notice. Continued use of the Platform after
              any modification constitutes your acceptance of the revised
              Disclaimer.
            </p>
          </section>

          {/* Box */}
          <div className="mt-10 rounded-lg border border-amber-200 bg-amber-50 p-5">
            <p className="text-sm font-semibold text-amber-900 mb-1">
              Always consult a qualified lawyer.
            </p>
            <p className="text-sm text-amber-800">
              No AI tool — including BeforeYouSign — can replace the advice of
              a licensed legal professional who understands the full context of
              your situation and the law of your jurisdiction.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
